# Generated by Django 3.2.8 on 2021-11-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookorigin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ['-created_at']},
        ),
    ]
