# Generated by Django 3.2.8 on 2021-11-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_bookorigin_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorigin',
            old_name='author',
            new_name='authors',
        ),
    ]
